classname: pipelines.tide_gauge.pipeline.Tide_Gauge

triggers:
  - .*tidegage.*\.log

retriever:
  path: pipelines/tide_gauge/config/retriever.yaml

dataset:
  path: pipelines/tide_gauge/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: pipelines/tide_gauge/config/storage.yaml
