classname: pipelines.adcp.pipeline.ADCP

triggers:
  - .*\.wpr

retriever:
  path: pipelines/adcp/config/retriever.yaml

dataset:
  path: pipelines/adcp/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: pipelines/adcp/config/storage.yaml
